# PostgreSQL Configuration for Docker
spring.datasource.url=jdbc:postgresql://postgres:5432/bankdb
spring.datasource.username=bankuser
spring.datasource.password=bankpass123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# SQL Init -
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGenerationAndValidation12345678901234567890
jwt.expiration=86400000

# Actuator
management.endpoints.web.exposure.include=prometheus,health,info,metrics
management.endpoint.health.show-details=always

management.endpoints.web.access.default=unrestricted

# Logging
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO
logging.level.com.example.bankwalletrestapi=DEBUG

